<?xml version="1.0" encoding="utf-8"?><Database Name="Flow" Class="FlowDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=THE-NB121-2020\SQLEXPRESS;Initial Catalog=Flow;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FlowConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Flow" Member="Flows">
    <Type Name="Flow">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AvatarUrl" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>